name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish x64
      run: dotnet publish Run8IndustryConfigEditor/Run8IndustryConfigEditor.csproj -c Release -o RICE64 --sc -f net6.0-windows -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
    - name: Publish x64
      run: dotnet publish Run8IndustryConfigEditor/Run8IndustryConfigEditor.csproj -c Release -o RICE64Slim --no-self-contained -f net6.0-windows -r win-x64
    - name: Upload x64 Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: RICE64
        path: RICE64/**
        if-no-files-found: warn
    - name: Upload x64 Slim Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: RICE64Slim
        path: RICE64Slim/**
        if-no-files-found: warn